services:
  db:
    image: postgres:14
    container_name: odoo_database
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped	 
  
  odoo:
    image: abhisharma1423/custom_odoo_image:
    depends_on:
      - db
    container_name: odoo_18
    ports:
      - 8003:8069
    stdin_open: true
    tty: true
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    command:
      ["odoo", "-c", "/etc/odoo/odoo.conf"]
    volumes:
      - odoo:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped	
   
volumes:
  postgres:
  odoo:
